<?php
/**
 * Contact Form Handler - PHP Backend
 * Receives JSON POST from the contact form and sends email notification.
 */

// CORS headers
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");
header("Content-Type: application/json; charset=UTF-8");

// Handle preflight OPTIONS request
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Only accept POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Method not allowed.']);
    exit();
}

// Read and decode JSON body
$input = file_get_contents('php://input');
$data  = json_decode($input, true);

if (!$data) {
    echo json_encode(['success' => false, 'message' => 'Invalid request data.']);
    exit();
}

// Sanitize helper
function clean($val) {
    return htmlspecialchars(strip_tags(trim((string)$val)), ENT_QUOTES, 'UTF-8');
}

// Extract fields
$name    = clean($data['name']    ?? '');
$email   = clean($data['email']   ?? '');
$phone   = clean($data['phone']   ?? '');
$subject = clean($data['subject'] ?? 'General Inquiry');
$message = clean($data['message'] ?? '');

// Validate required fields
if (!$name) {
    echo json_encode(['success' => false, 'message' => 'Name is required.']);
    exit();
}
if (!$email || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    echo json_encode(['success' => false, 'message' => 'A valid email address is required.']);
    exit();
}
if (!$message) {
    echo json_encode(['success' => false, 'message' => 'Message is required.']);
    exit();
}

// Build HTML email body
$htmlBody = "
<html><body style='font-family:Arial,sans-serif;color:#333;'>
<h2 style='color:#1d2a44;'>New Contact Form Message</h2>
<p>Submitted on: <strong>" . date('d M Y, h:i A') . "</strong></p>

<table style='width:100%;border-collapse:collapse;'>
  <tr><td style='padding:8px 12px;font-weight:bold;width:140px;background:#f8f9fa;'>Name</td><td style='padding:8px 12px;'>{$name}</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#fff;'>Email</td><td style='padding:8px 12px;'>{$email}</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#f8f9fa;'>Phone</td><td style='padding:8px 12px;'>" . ($phone ?: 'N/A') . "</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#fff;'>Subject</td><td style='padding:8px 12px;'>{$subject}</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#f8f9fa;vertical-align:top;'>Message</td><td style='padding:8px 12px;white-space:pre-wrap;'>{$message}</td></tr>
</table>

<br><hr>
<p style='color:#888;font-size:12px;'>This email was automatically generated by the SG Education website contact form.</p>
</body></html>
";

// Send email
$toEmail = 'inymartlabs@gmail.com';
$mailSubject = "Contact Form: {$subject} - {$name}";

$headers = implode("\r\n", [
    "From: {$name} <{$email}>",
    "Reply-To: {$email}",
    "MIME-Version: 1.0",
    "Content-Type: text/html; charset=UTF-8",
    "X-Mailer: PHP/" . phpversion(),
]);

$mailSent = mail($toEmail, $mailSubject, $htmlBody, $headers);

if ($mailSent) {
    echo json_encode(['success' => true, 'message' => 'Your message has been sent successfully!']);
} else {
    error_log("Contact form mail() failed for: {$name} <{$email}>");
    // Still return success so user isn't confused — log the failure server-side
    echo json_encode(['success' => true, 'message' => 'Message received. We will get back to you shortly.']);
}
?>
