<?php
/**
 * Contact Form Handler - PHP Backend
 * Receives JSON POST from the contact form and sends email via PHPMailer SMTP.
 */

// Output buffering to prevent stray output from corrupting JSON
ob_start();
ini_set('display_errors', 0);
error_reporting(E_ALL);

// CORS headers
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");
header("Content-Type: application/json; charset=UTF-8");

// Handle preflight OPTIONS request
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Only accept POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Method not allowed.']);
    exit();
}

// Load config (SMTP constants)
require_once __DIR__ . '/config.php';

// Load PHPMailer helper
require_once __DIR__ . '/mailer.php';

// Read and decode JSON body
$input = file_get_contents('php://input');
$data  = json_decode($input, true);

if (!$data) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Invalid request data.']);
    exit();
}

// Sanitize helper
function clean($val) {
    return htmlspecialchars(strip_tags(trim((string)$val)), ENT_QUOTES, 'UTF-8');
}

// Extract fields
$name    = clean($data['name']    ?? '');
$email   = clean($data['email']   ?? '');
$phone   = clean($data['phone']   ?? '');
$subject = clean($data['subject'] ?? 'General Inquiry');
$message = clean($data['message'] ?? '');

// Validate
if (!$name) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Name is required.']);
    exit();
}
if (!$email || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'A valid email address is required.']);
    exit();
}
if (!$message) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Message is required.']);
    exit();
}

// ── Save to database (non-fatal if it fails) ─────────────────────────────────
try {
    // Auto-create table if it doesn't exist (helpful for Hostinger deployment)
    $pdo->exec("CREATE TABLE IF NOT EXISTS `contacts` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(255) NOT NULL,
      `email` varchar(255) NOT NULL,
      `phone` varchar(50) DEFAULT NULL,
      `subject` varchar(255) DEFAULT NULL,
      `message` text NOT NULL,
      `submitted_at` datetime DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

    $stmt = $pdo->prepare("
        INSERT INTO contacts (name, email, phone, subject, message, submitted_at)
        VALUES (?, ?, ?, ?, ?, NOW())
    ");
    $stmt->execute([$name, $email, $phone, $subject, $message]);
} catch (Exception $e) {
    error_log('Contact DB save error: ' . $e->getMessage());
}
// ── Build HTML email body ─────────────────────────────────────────────────────
$htmlBody = "
<html><body style='font-family:Arial,sans-serif;color:#333;'>
<h2 style='color:#1d2a44;'>New Contact Form Message</h2>
<p>Submitted on: <strong>" . date('d M Y, h:i A') . "</strong></p>

<table style='width:100%;border-collapse:collapse;'>
  <tr><td style='padding:8px 12px;font-weight:bold;width:140px;background:#f8f9fa;'>Name</td><td style='padding:8px 12px;'>{$name}</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#fff;'>Email</td><td style='padding:8px 12px;'><a href='mailto:{$email}'>{$email}</a></td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#f8f9fa;'>Phone</td><td style='padding:8px 12px;'>" . ($phone ?: 'N/A') . "</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#fff;'>Subject</td><td style='padding:8px 12px;'>{$subject}</td></tr>
  <tr><td style='padding:8px 12px;font-weight:bold;background:#f8f9fa;vertical-align:top;'>Message</td><td style='padding:8px 12px;white-space:pre-wrap;'>{$message}</td></tr>
</table>

<br><hr>
<p style='color:#888;font-size:12px;'>This email was automatically generated by the SG Education website contact form.</p>
</body></html>
";

$plainText = "Name: {$name}\nEmail: {$email}\nPhone: " . ($phone ?: 'N/A') . "\nSubject: {$subject}\n\nMessage:\n{$message}";

// ── Send email via PHPMailer SMTP ────────────────────────────────────────────
try {
    $mail = createMailer();

    // Recipient
    // Add all recipients defined in config
    $recipients = explode(',', MAIL_TO);
    foreach ($recipients as $recipient) {
        $mail->addAddress(trim($recipient), 'Admin');
    }

    // Reply-To so you can directly reply to the sender
    $mail->addReplyTo($email, $name);

    // Subject & body
    $mail->Subject = "Contact Form: {$subject} — {$name}";
    $mail->Body    = $htmlBody;
    // Clear stray output before sending JSON
    if (ob_get_length()) ob_end_clean();

    $mail->send();
    echo json_encode(['success' => true, 'message' => 'Message sent successfully! We will contact you shortly.']);

} catch (\PHPMailer\PHPMailer\Exception $e) {
    if (ob_get_length()) ob_end_clean();
    error_log('Contact PHPMailer error: ' . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'SMTP Error: ' . $e->getMessage()]);
} catch (\Throwable $e) {
    if (ob_get_length()) ob_end_clean();
    error_log('Contact general error: ' . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'Server Crash: ' . $e->getMessage() . ' in ' . $e->getFile() . ' on line ' . $e->getLine()]);
}
?>
